# Generated by Django 5.2 on 2025-04-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='mileage',
            field=models.CharField(max_length=100),
        ),
    ]
