# Generated by Django 5.2 on 2025-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rims',
            field=models.ManyToManyField(to='main_app.rim'),
        ),
    ]
